# RetailPulse AI – Day 23: Kubernetes Deployment Configuration

### Prepared By: Bansi Kanani

### Date: 20 June 2026

## Objective

The objective of this notebook is to understand Kubernetes deployment and create deployment manifests for the RetailPulse AI application.

Kubernetes automates application deployment, scaling, load balancing, and management of containerized applications in production environments.

In [1]:
import pandas as pd

print("RetailPulse AI - Kubernetes Deployment")

RetailPulse AI - Kubernetes Deployment

## What is Kubernetes?

Kubernetes is an open-source container orchestration platform that manages Docker containers automatically.

It provides:

- Automated deployment
- Auto scaling
- Load balancing
- High availability
- Self healing
- Easy updates and rollbacks

In [2]:
k8s = pd.DataFrame({

    "Feature":[
        "Auto Scaling",
        "Load Balancing",
        "Self Healing",
        "Rolling Updates",
        "Service Discovery",
        "High Availability"
    ],

    "Description":[
        "Automatically scale pods",
        "Distributes incoming traffic",
        "Restarts failed containers",
        "Zero downtime deployment",
        "Connects services",
        "Runs multiple replicas"
    ]

})

k8s

             Feature                   Description
0       Auto Scaling      Automatically scale pods
1     Load Balancing  Distributes incoming traffic
2       Self Healing    Restarts failed containers
3    Rolling Updates      Zero downtime deployment
4  Service Discovery             Connects services
5  High Availability        Runs multiple replicas

## Kubernetes Components

- Pod
- Deployment
- Service
- ReplicaSet
- Namespace
- Node
- Cluster

In [3]:
deployment_yaml = """

apiVersion: apps/v1

kind: Deployment

metadata:

  name: retailpulse-ai

spec:

  replicas: 2

  selector:

    matchLabels:

      app: retailpulse

  template:

    metadata:

      labels:

        app: retailpulse

    spec:

      containers:

      - name: retailpulse

        image: retailpulse-ai:latest

        ports:

        - containerPort: 8501

"""

print(deployment_yaml)

apiVersion: apps/v1

kind: Deployment

metadata:

  name: retailpulse-ai

spec:

  replicas: 2

  selector:

    matchLabels:

      app: retailpulse

  template:

    metadata:

      labels:

        app: retailpulse

    spec:

      containers:

      - name: retailpulse

        image: retailpulse-ai:latest

        ports:

        - containerPort: 8501

In [4]:
with open("deployment.yaml","w") as file:

    file.write(deployment_yaml)

print("deployment.yaml created successfully.")

deployment.yaml created successfully.

In [5]:
service_yaml = """

apiVersion: v1

kind: Service

metadata:

  name: retailpulse-service

spec:

  selector:

    app: retailpulse

  ports:

  - protocol: TCP

    port: 80

    targetPort: 8501

  type: LoadBalancer

"""

print(service_yaml)

apiVersion: v1

kind: Service

metadata:

  name: retailpulse-service

spec:

  selector:

    app: retailpulse

  ports:

  - protocol: TCP

    port: 80

    targetPort: 8501

  type: LoadBalancer

In [6]:
with open("service.yaml","w") as file:

    file.write(service_yaml)

print("service.yaml created successfully.")

service.yaml created successfully.

## Kubernetes Commands

Apply deployment

```bash
kubectl apply -f deployment.yaml
```

Apply service

```bash
kubectl apply -f service.yaml
```

View pods

```bash
kubectl get pods
```

View services

```bash
kubectl get services
```

Delete deployment

```bash
kubectl delete deployment retailpulse-ai
```

In [7]:
workflow = pd.DataFrame({

    "Step":[
        "Source Code",
        "Docker Image",
        "Kubernetes Deployment",
        "Pods",
        "Service",
        "Business Users"
    ],

    "Purpose":[
        "RetailPulse AI",
        "Container Package",
        "Deploy Application",
        "Run Containers",
        "Expose Application",
        "Access Dashboard"
    ]

})

workflow

                    Step             Purpose
0            Source Code      RetailPulse AI
1           Docker Image   Container Package
2  Kubernetes Deployment  Deploy Application
3                   Pods      Run Containers
4                Service  Expose Application
5         Business Users    Access Dashboard

Source Code (app.py) -> Docker Image -> Kubernetes Deployment -> Pod -> Service -> Business Users

## Architecture Explanation

The RetailPulse AI application is packaged as a Docker image and deployed to a Kubernetes cluster using a Deployment manifest.

Kubernetes creates multiple pods to ensure high availability. A LoadBalancer Service exposes the application to end users and distributes traffic across the running pods.

This architecture provides scalability, fault tolerance, automatic recovery, and production-ready deployment.

In [8]:
advantages = pd.DataFrame({

    "Business Benefit":[
        "Scalability",
        "High Availability",
        "Fault Tolerance",
        "Automatic Recovery",
        "Load Balancing",
        "Production Deployment"
    ],

    "Impact":[
        "Handles more users",
        "24x7 availability",
        "No downtime",
        "Restarts failed pods",
        "Distributes traffic",
        "Cloud ready"
    ]

})

advantages

        Business Benefit                Impact
0            Scalability    Handles more users
1      High Availability     24x7 availability
2        Fault Tolerance           No downtime
3     Automatic Recovery  Restarts failed pods
4         Load Balancing   Distributes traffic
5  Production Deployment           Cloud ready

## Conclusion

Kubernetes simplifies the deployment and management of containerized applications by providing automated scaling, self-healing, and load balancing.

For RetailPulse AI, Kubernetes ensures reliable, scalable, and production-ready deployment, making the analytics platform suitable for enterprise environments.