# RetailPulse AI – Day 7: Week 1 Checkpoint & MLflow Experiment Tracking

### Prepared By: Bansi Kanani

### Date: 04 June 2026

# Introduction

Machine Learning Operations (MLOps) focuses on tracking, managing, and monitoring machine learning experiments.

This notebook demonstrates experiment tracking using MLflow for Prophet and LSTM forecasting models.

# Objective

The objectives of Day 7 are:

- Introduce MLflow experiment tracking
- Log Prophet model metrics
- Log LSTM model metrics
- Compare forecasting models
- Create a Week 1 checkpoint

In [1]:
import mlflow
import pandas as pd

c:\Users\07mee\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
mlflow.set_experiment(
    "RetailPulse_Week1"
)

<Experiment: artifact_location='file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO INTERNSHIP/mlruns/1', creation_time=1780987690195, experiment_id='1', last_update_time=1780987690195, lifecycle_stage='active', name='RetailPulse_Week1', tags={}, trace_location=None, workspace='default'>

# Prophet Experiment Logging

In [3]:
with mlflow.start_run(
    run_name="Prophet_Model"
):

    mlflow.log_param(
        "model_type",
        "Prophet"
    )

    mlflow.log_param(
        "forecast_horizon",
        30
    )

    mlflow.log_metric(
        "mape",
        39.40
    )

print(
    "Prophet experiment logged."
)

Prophet experiment logged.

# LSTM Experiment Logging

In [4]:
with mlflow.start_run(
    run_name="LSTM_Model"
):

    mlflow.log_param(
        "model_type",
        "LSTM"
    )

    mlflow.log_param(
        "epochs",
        100
    )

    mlflow.log_param(
        "sequence_length",
        12
    )

    mlflow.log_metric(
        "rmse",
        21232.65
    )

print(
    "LSTM experiment logged."
)

LSTM experiment logged.

In [5]:
import mlflow

client = mlflow.tracking.MlflowClient()

client.search_experiments()

[<Experiment: artifact_location='file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO INTERNSHIP/mlruns/1', creation_time=1780987690195, experiment_id='1', last_update_time=1780987690195, lifecycle_stage='active', name='RetailPulse_Week1', tags={}, trace_location=None, workspace='default'>,
 <Experiment: artifact_location='file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO INTERNSHIP/mlruns/0', creation_time=1780987690185, experiment_id='0', last_update_time=1780987690185, lifecycle_stage='active', name='Default', tags={}, trace_location=None, workspace='default'>]

In [6]:
runs = mlflow.search_runs()

runs

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.rmse,metrics.mape,params.model_type,params.epochs,params.sequence_length,params.forecast_horizon,tags.mlflow.source.name,tags.mlflow.source.type,tags.mlflow.runName,tags.mlflow.user
0,76f724a0bf704c729439c44a5425fbd6,1,FINISHED,file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO ...,2026-06-11 06:11:02.022000+00:00,2026-06-11 06:11:02.093000+00:00,21232.65,NaN,LSTM,100,12,None,Day7_Week1_Checkpoint_MLflow.ipynb,NOTEBOOK,LSTM_Model,07mee
1,f18d936e65a24102b77420468dfcd478,1,FINISHED,file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO ...,2026-06-11 06:11:01.925000+00:00,2026-06-11 06:11:01.988000+00:00,NaN,39.4,Prophet,None,None,30,Day7_Week1_Checkpoint_MLflow.ipynb,NOTEBOOK,Prophet_Model,07mee
2,45c81040379e43a3835c678baac9e2f8,1,FINISHED,file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO ...,2026-06-09 09:37:35.361000+00:00,2026-06-09 09:37:35.454000+00:00,21232.65,NaN,LSTM,100,12,None,Day7_Week1_Checkpoint_MLflow.ipynb,NOTEBOOK,LSTM_Model,07mee
3,8f202e1a6fe5492588c3d2709be52c46,1,FINISHED,file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO ...,2026-06-09 09:37:35.102000+00:00,2026-06-09 09:37:35.279000+00:00,NaN,39.4,Prophet,None,None,30,Day7_Week1_Checkpoint_MLflow.ipynb,NOTEBOOK,Prophet_Model,07mee
4,1d79be0835024fbaaa1b13bcec446333,1,FINISHED,file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO ...,2026-06-09 06:56:24.889000+00:00,2026-06-09 06:56:24.948000+00:00,21232.65,NaN,LSTM,100,12,None,Day7_Week1_Checkpoint_MLflow.ipynb,NOTEBOOK,LSTM_Model,07mee
5,42a1c67b7589474d937221e2f331614e,1,FINISHED,file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO ...,2026-06-09 06:56:24.763000+00:00,2026-06-09 06:56:24.847000+00:00,NaN,39.4,Prophet,None,None,30,Day7_Week1_Checkpoint_MLflow.ipynb,NOTEBOOK,Prophet_Model,07mee
6,9e8291c01740483e8144761661478964,1,FINISHED,file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO ...,2026-06-09 06:48:15.598000+00:00,2026-06-09 06:48:15.665000+00:00,21232.65,NaN,LSTM,100,12,None,Day7_Week1_Checkpoint_MLflow.ipynb,NOTEBOOK,LSTM_Model,07mee
7,052f99645599417f832cc79912a2220d,1,FINISHED,file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO ...,2026-06-09 06:48:12.545000+00:00,2026-06-09 06:48:12.601000+00:00,NaN,39.4,Prophet,None,None,30,Day7_Week1_Checkpoint_MLflow.ipynb,NOTEBOOK,Prophet_Model,07mee

# Experiment Summary

In [7]:
runs = mlflow.search_runs()

runs

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.rmse,metrics.mape,params.model_type,params.epochs,params.sequence_length,params.forecast_horizon,tags.mlflow.source.name,tags.mlflow.source.type,tags.mlflow.runName,tags.mlflow.user
0,76f724a0bf704c729439c44a5425fbd6,1,FINISHED,file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO ...,2026-06-11 06:11:02.022000+00:00,2026-06-11 06:11:02.093000+00:00,21232.65,NaN,LSTM,100,12,None,Day7_Week1_Checkpoint_MLflow.ipynb,NOTEBOOK,LSTM_Model,07mee
1,f18d936e65a24102b77420468dfcd478,1,FINISHED,file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO ...,2026-06-11 06:11:01.925000+00:00,2026-06-11 06:11:01.988000+00:00,NaN,39.4,Prophet,None,None,30,Day7_Week1_Checkpoint_MLflow.ipynb,NOTEBOOK,Prophet_Model,07mee
2,45c81040379e43a3835c678baac9e2f8,1,FINISHED,file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO ...,2026-06-09 09:37:35.361000+00:00,2026-06-09 09:37:35.454000+00:00,21232.65,NaN,LSTM,100,12,None,Day7_Week1_Checkpoint_MLflow.ipynb,NOTEBOOK,LSTM_Model,07mee
3,8f202e1a6fe5492588c3d2709be52c46,1,FINISHED,file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO ...,2026-06-09 09:37:35.102000+00:00,2026-06-09 09:37:35.279000+00:00,NaN,39.4,Prophet,None,None,30,Day7_Week1_Checkpoint_MLflow.ipynb,NOTEBOOK,Prophet_Model,07mee
4,1d79be0835024fbaaa1b13bcec446333,1,FINISHED,file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO ...,2026-06-09 06:56:24.889000+00:00,2026-06-09 06:56:24.948000+00:00,21232.65,NaN,LSTM,100,12,None,Day7_Week1_Checkpoint_MLflow.ipynb,NOTEBOOK,LSTM_Model,07mee
5,42a1c67b7589474d937221e2f331614e,1,FINISHED,file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO ...,2026-06-09 06:56:24.763000+00:00,2026-06-09 06:56:24.847000+00:00,NaN,39.4,Prophet,None,None,30,Day7_Week1_Checkpoint_MLflow.ipynb,NOTEBOOK,Prophet_Model,07mee
6,9e8291c01740483e8144761661478964,1,FINISHED,file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO ...,2026-06-09 06:48:15.598000+00:00,2026-06-09 06:48:15.665000+00:00,21232.65,NaN,LSTM,100,12,None,Day7_Week1_Checkpoint_MLflow.ipynb,NOTEBOOK,LSTM_Model,07mee
7,052f99645599417f832cc79912a2220d,1,FINISHED,file:///c:/Users/07mee/OneDrive/Desktop/ZIDIO ...,2026-06-09 06:48:12.545000+00:00,2026-06-09 06:48:12.601000+00:00,NaN,39.4,Prophet,None,None,30,Day7_Week1_Checkpoint_MLflow.ipynb,NOTEBOOK,Prophet_Model,07mee

# Week 1 Achievements

Completed:

- Exploratory Data Analysis
- Data Cleaning & Feature Engineering
- RFM Customer Segmentation
- Time-Series Preparation
- Prophet Forecasting
- LSTM Forecasting
- MLflow Experiment Tracking

This concludes Week 1 of the RetailPulse AI project.

# Business Insights

1. Customer segmentation identified valuable customer groups.

2. Time-series analysis revealed trend and seasonal patterns.

3. Prophet and LSTM models successfully generated demand forecasts.

4. MLflow enables reproducible experiment tracking and model comparison.

5. The project is ready for monitoring and model governance activities.

# Conclusion

Week 1 objectives were successfully completed.

The RetailPulse AI project now includes customer analytics, forecasting models, and experiment tracking capabilities, providing a strong foundation for advanced MLOps activities in the following weeks.